"""empty message

Revision ID: 090770a706e7
Revises: 9b3c573f7cde
Create Date: 2021-05-17 16:44:50.972332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090770a706e7'
down_revision = '9b3c573f7cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'title')
    # ### end Alembic commands ###
