"""empty message

Revision ID: 1d6d6afc1a38
Revises: 85867074f03c
Create Date: 2021-06-12 00:43:20.806645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6d6afc1a38'
down_revision = '85867074f03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_text', 'math')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_text', sa.Column('math', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
