"""empty message

Revision ID: 795a96030b62
Revises: 83636b71b5a4
Create Date: 2021-06-17 01:00:27.894091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795a96030b62'
down_revision = '83636b71b5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_day', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_day', 'total')
    # ### end Alembic commands ###
