"""empty message

Revision ID: 83636b71b5a4
Revises: 1d6d6afc1a38
Create Date: 2021-06-14 23:05:19.097336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83636b71b5a4'
down_revision = '1d6d6afc1a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('memory', sa.Column('time', sa.Text(), nullable=True))
    op.add_column('memory', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('memory', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'memory', 'user', ['user_id'], ['id'])
    op.add_column('user_day', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_day', 'score')
    op.drop_constraint(None, 'memory', type_='foreignkey')
    op.drop_column('memory', 'user_id')
    op.drop_column('memory', 'updated_at')
    op.drop_column('memory', 'time')
    op.drop_column('memory', 'created_at')
    # ### end Alembic commands ###
