"""empty message

Revision ID: 85867074f03c
Revises: 090770a706e7
Create Date: 2021-06-12 00:31:19.848747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85867074f03c'
down_revision = '090770a706e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_text', sa.Column('math', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_text', 'math')
    # ### end Alembic commands ###
