"""empty message

Revision ID: 9b3c573f7cde
Revises: 
Create Date: 2021-05-17 16:09:02.770131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3c573f7cde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_day', sa.Column('day_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_day', 'day', ['day_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_day', type_='foreignkey')
    op.drop_column('user_day', 'day_id')
    # ### end Alembic commands ###
